language: python

python:
  - 2.7.13

install:
  - pip install -r requirements.txt

script:
  - py.test --cov-report term-missing --cov app -v


after_success:
  - coveralls
  - codecov --file coverage/lcov.info --disable search



